### ISSUE TITLE
Using unhead alongside `useServerSeoMeta` ?

### ISSUE THREAD

**Issue by lewebsimple** [harlan-zw/nuxt-unhead#5]
### Details

I'm trying to wrap my head around SEO best practices with Nuxt and I'm a little confused about the right way to set page title, ogTitle, etc.

While Nuxt provides `useServerSeoMeta` to set meta fields, this project makes the whole process a lot easier / cleaner. But will the two approaches interfere or can I combine them in the same project ?

Thanks!

**Comment by harlan-zw** [comment]
Nope, they are compatible. Nuxt and this module both use [Unhead](https://unhead.harlanzw.com/), this module just implements some of the experimental features.

Both are fully compatible though.

With the latest version of this package, it will actually extract title and titleTemplate from `useServerSeoMeta`, which should make it more compatible.
