### ISSUE TITLE
Does not work well with Content

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-unhead#7]
### Describe the bug

Here my config

```
  runtimeConfig: {
    public: {
      trailingSlash: true,
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || 'https://example.com',
      titleSeparator: '|',
      siteName: 'Awesome Site',
      siteDescription: 'Welcome to my awesome site!',
      language: 'fr-FR', // prefer more explicit language codes like `en-AU` over `en`
    }
  },
```

and here the result : 
![image](https://user-images.githubusercontent.com/45267552/221375208-6270ce45-b8d2-4b7a-8aa2-a9bbf0aa03ad.png)

### Reproduction

/

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.70 GB / 7.68 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.2 - /usr/bin/node
    Yarn: 1.22.19 - /mnt/c/Users/esoub/AppData/Roaming/npm/yarn
    npm: 9.5.1 - /usr/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Barbapapazes** [comment]
Don't understand why this happen because it works well on stackblitz

**Comment by Barbapapazes** [comment]
I'm currently building a layer using your layer and in the playground, nothing works well.

**Comment by harlan-zw** [comment]
Hey @Barbapapazes, thanks for the issue.

This seems like an problem with the version of unhead you're using.

Would you mind trying with the latest version or nuxt-unhead (1.4.6) / nuxt-seo-kit (1.3.1) (if using)? You should probably delete your lock file + re-install it as well.

If you still have issues, can you check what version of unhead is being used `npm why unhead`

**Comment by Barbapapazes** [comment]
Yep, I'm using nuxt-seo-kit ! I try this and let you know

**Comment by Barbapapazes** [comment]
Here the result of `npm why unhead` after removing the lock file.

```
[more than 1200 lines]
unhead@1.1.8
node_modules/.pnpm/@unhead+vue@1.1.8/node_modules/unhead
  unhead@"1.1.8" from @unhead/vue@1.1.8
  node_modules/.pnpm/@unhead+vue@1.1.8/node_modules/@unhead/vue
    @unhead/vue@1.1.8
    node_modules/.pnpm/@vueuse+head@1.1.8/node_modules/@unhead/vue
      @unhead/vue@"^1.1.8" from @vueuse/head@1.1.8
      node_modules/.pnpm/@vueuse+head@1.1.8/node_modules/@vueuse/head
        @vueuse/head@1.1.8
        node_modules/.pnpm/nuxt-unhead@1.4.6/node_modules/@vueuse/head
          @vueuse/head@"^1.1.8" from nuxt-unhead@1.4.6
          node_modules/.pnpm/nuxt-unhead@1.4.6/node_modules/nuxt-unhead
            nuxt-unhead@1.4.6
            node_modules/nuxt-unhead
            nuxt-unhead@1.4.6
            node_modules/.pnpm/nuxt-seo-kit@1.3.1/node_modules/nuxt-unhead
              nuxt-unhead@"^1.4.6" from nuxt-seo-kit@1.3.1
              node_modules/.pnpm/nuxt-seo-kit@1.3.1/node_modules/nuxt-seo-kit
                nuxt-seo-kit@1.3.1
                node_modules/nuxt-seo-kit
                  nuxt-seo-kit@"^1.3.1" from the root project
```

**Comment by Barbapapazes** [comment]
Will try to add a reproduction (but here my repo where I get this issue: https://github.com/Classement-des-Associations/website-theme). I will use nuxt-seo-kit.

**Comment by Barbapapazes** [comment]
Okkk, so here, it works well: https://stackblitz.com/edit/nuxt-starter-63cukj?file=.playground/nuxt.config.ts

**Comment by Barbapapazes** [comment]
Niiice ! 
![image](https://user-images.githubusercontent.com/45267552/221397305-b4b0b505-ef7f-4445-a81d-6ff8e9d4b380.png)

I think that .nuxt folder was using last version. I see many time the nuxi cleanup but I really should use it! 

Thanks a lot @harlan-zw for your fast response! 👌

**Comment by Barbapapazes** [comment]
I tried to change the `app.head.titleTemplate` with %pageTitle but it doesn't change my tab title

![image](https://user-images.githubusercontent.com/45267552/221609507-dad24bdf-bb15-4d72-ae76-e241c21e3cb2.png)
![Uploading image.png…]()

**Comment by Barbapapazes** [comment]
With this 
![image](https://user-images.githubusercontent.com/45267552/221612166-309947e5-e6a4-4413-96bd-bc940dd7b2fd.png)


I got this
![image](https://user-images.githubusercontent.com/45267552/221612297-7ac4c4d7-be85-44f3-84b0-2085c688f20f.png)

Very strange

**Comment by Barbapapazes** [comment]
Sooo, on stackblitz, it's still working. Strange.

**Comment by Barbapapazes** [comment]
Using my theme, it seems to work too on stackblitz https://stackblitz.com/edit/nuxt-starter-smpdta?file=nuxt.config.ts

Very very strange behavior

**Comment by Barbapapazes** [comment]
Whooo it was an issue with my lock file (a last version of unhead was used).
